export const navItems = [
  {
    name: "About",
    link: "#about",
    icon: "bxs-user-circle",
  },
  { name: "Experience", link: "#experience", icon: "bx-briefcase-alt-2" },
  { name: "Portfolio", link: "#portfolio", icon: "bxs-category" },
  { name: "Contacts", link: "#contacts", icon: "bxs-contact" },
  { name: "Resume", link: "#resume", icon: "bx-notepad" },
];

export const gridItems = [
  {
    id: 1,
    title: "I prioritize client collaboration, fostering open communication ",
    description: "",
    className: "lg:col-span-3 md:col-span-6 md:row-span-4 lg:min-h-[60vh]",
    imgClassName: "w-full h-full",
    titleClassName: "justify-end",
    img: "/b1.svg",
    spareImg: "",
  },
  {
    id: 2,
    title: "I'm very flexible with time zone communications",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "",
    titleClassName: "justify-start",
    img: "",
    spareImg: "",
  },
  {
    id: 3,
    title: "My tech stack",
    description: "I constantly try to improve",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
  },
  {
    id: 4,
    title: "Tech enthusiast with a passion for development.",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    imgClassName: "",
    titleClassName: "justify-start",
    img: "/grid.svg",
    spareImg: "/b4.svg",
  },

  {
    id: 5,
    title: "Currently building a JS Animation library",
    description: "The Inside Scoop",
    className: "md:col-span-3 md:row-span-2",
    imgClassName: "absolute right-0 bottom-0 md:w-96 w-60",
    titleClassName: "justify-center md:justify-start lg:justify-center",
    img: "/b5.svg",
    spareImg: "/grid.svg",
  },
  {
    id: 6,
    title: "Do you want to start a project together?",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    imgClassName: "",
    titleClassName: "justify-center md:max-w-full max-w-60 text-center",
    img: "",
    spareImg: "",
  },
];

export const projects = [
  {
    folder: "/proj1.webp",
    folder2: "/proja.png",
    name: "proj1",
    type: "frontend",
    title: "HooBank",
    stack: "ReactJs / NodeJs",
    description:
      "In a world driven by economic dynamics, mastering the art of financial management is paramount. This project delves into the intricacies of handling finances and navigating the banking system, offering insights to empower individuals in achieving fiscal stability and making informed financial decisions",
    link: "hoobank-rouge.vercel.app",
  },
  {
    folder: "/proj2.jpg",
    folder2: "/projb.png",
    name: "proj2",
    type: "fullstack",
    title: "LearnAIPrompts",
    stack: "NextJs / ExpressJs",
    description:
      "Embarking on the frontier of artificial intelligence, this project explores the nuanced realm of optimizing AI prompts for enhanced learning outcomes from different users who have different perspectives and ideas. By dissecting and refining the intricacies of AI-generated prompts, we aim to unlock the full potential of machine learning algorithms, fostering a more intuitive and effective utilization of AI technologies in diverse applications",
    link: "learnaiprompts.vercel.app",
  },
  {
    folder: "/proj4.jpg",
    folder2: "/projd.png",
    name: "proj4",
    type: "frontend",
    title: "Omale",
    stack: "Js / Tailwind",
    description:
      "Embarking on the intersection of aesthetics and functionality, this frontend project is a visual symphony, meticulously designed to elevate the user experience in login and signup interactions. With a focus on seamless navigation and captivating design, the project aims to redefine the aesthetics of user authentication, harmonizing beauty and structure for an unparalleled frontend journey.",
    link: "yunjin08.github.io/odin-project/",
  },
  {
    folder: "/portfolio.png",
    folder2: "/proje.png",
    name: "proj5",
    type: "frontend",
    title: "PortfoTemp",
    stack: "Js / Tailwind",
    description:
      "This project encompasses a meticulously crafted portfolio template, meticulously designed to showcase your professional achievements and creative endeavors. With a sleek and modern aesthetic, the template is not only visually appealing but also user-friendly, allowing you to effortlessly present your work, skills, and experiences.",
    link: "yunjin08.github.io/Second-Odin-Project/",
  },
  {
    folder: "/proj6.jpg",
    folder2: "/projf.png",
    name: "proj6",
    type: "fullstack",
    title: "Library Stack",
    stack: "NextJs / Expressjs",
    description:
      "    Embarking on a journey through the literary landscape, this frontend project redefines the way we engage with books, providing an aesthetically pleasing and user-friendly platform to manage and track your reading adventures. Seamlessly blending functionality and design, the project enables users to curate their reading lists, marking each book with a personalized touch to effortlessly navigate the world of literature and keep a visual record of completed reads.",
    link: "libstack.vercel.app",
  },
  {
    folder: "/proj7.jpg",
    folder2: "/projg.png",
    name: "proj7",
    type: "fullstack",
    title: "NoshNest",
    stack: "VueJS / ExpressJS",
    description:
      "NoshNest is an innovative online platform designed to elevate your culinary experience by offering a diverse collection of recipes and a user-friendly food menu. Whether you're a seasoned chef or a kitchen novice, NoshNest aims to inspire, guide, and simplify the art of cooking, making every meal a delightful adventure.",
    link: "noshnest.vercel.app",
  },
  {
    folder: "/proj8.webp",
    folder2: "/projh.webp",
    name: "proj8",
    type: "fullstack",
    title: "Linkup",
    stack: "Nextjs / GetStream IO",
    description:
      "Linkup, an innovative online conference platform, leverages Clerk for secure authentication and enhances its real-time communication capabilities using the GetStream.io library.",
    link: "linkup-connect.vercel.app",
  },
  {
    folder: "/proj9.webp",
    folder2: "/proji.png",
    name: "proj9",
    type: "fullstack",
    title: "FAVisualizer",
    stack: "Nextjs / React-flow",
    description:
      "A visualizer for generating DFA diagrams from regular expressions converts given regular expressions into their corresponding deterministic finite automata and presents them as visual diagrams. \
       This tool helps users understand the structure and behavior of DFAs by providing an interactive and graphical representation.",
    link: "favisualizer.vercel.app",
  },
  {
    folder: "/proj10.webp",
    folder2: "/projj.png",
    name: "proj10",
    type: "fullstack",
    title: "Beacon",
    stack: "GPT4 / Langchain",
    description:
      "A career guidance web app that uses Generative AI creates personalized visual roadmaps for users, guiding them toward viable career options based on their individual information. This tool \
       leverages AI to analyze user data and generate tailored career paths, helping users navigate their professional journey with clear and customized steps.",
    link: "beaconph.site",
  },
];

export const stacks = [
  { source: "/html.svg", id: "html", name: "HTML", use: "Frontend" },
  { source: "/css.png", id: "css", name: "CSS", use: "Frontend" },
  { source: "/js.svg", id: "js", name: "Javascript", use: "Frontend" },
  { source: "/c++.png", id: "c++", name: "C++", use: "Backend" },
  { source: "/python.png", id: "python", name: "Python", use: "Backend" },
  {
    source: "/rstud.svg",
    id: "rstud",
    name: "Rstudio",
    use: "Data Science",
  },
  {
    source: "/tailwind.png",
    id: "tailwind",
    name: "Tailwind",
    use: "Frontend",
  },
  { source: "/react.png", id: "react", name: "ReactJs", use: "Frontend" },
  { source: "/vuejs.svg", id: "vuejs", name: "VueJS", use: "Frontend" },
  { source: "/nextjs.svg", id: "nextjs", name: "NextJs", use: "Fullstack" },
  { source: "/nodejs.svg", id: "nodejs", name: "NodeJs", use: "Backend" },
  {
    source: "/expressjs.svg",
    id: "expressjs",
    name: "ExpressJs",
    use: "Backend",
  },
  {
    source: "/django.svg",
    id: "django",
    name: "Django",
    use: "Backend",
  },
  { source: "/mongodb.svg", id: "mongodb", name: "Mongodb", use: "Database" },
  {
    source: "/postgresql.svg",
    id: "postgresql",
    name: "Postgresql",
    use: "Database",
  },
  { source: "/vscode.svg", id: "vscode", name: "VSCode", use: "Code Editor" },
  {
    source: "/typescript.svg",
    id: "typescript",
    name: "Typescript",
    use: "Frontend Extension",
  },
  {
    source: "/postman.svg",
    id: "postman",
    name: "Postman",
    use: "API Client",
  },
];
